server:
  port: 8080

logging:
  level:
    root: WARN
    api.pokemon: INFO

springdoc:
  swagger-ui:
    enabled: false

pokemon-limit-retrive: 100

services:
  pokemon:
    base-url: https://pokeapi.co/api/v2/